[build]
# rustflags = ["-C", "prefer-dynamic", "-C", "rpath"]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup", "-C", "rpath"]
rustc-wrapper = "sccache"

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
